<a href="https://colab.research.google.com/github/123rabida123/Deep-Learning/blob/main/DeepLearning_Mai24-05%3A22%3A38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import mnist

In [ ]:
(train_images, train_labels), ( test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
# model architecture
from keras import models, layers

In [ ]:
network = models.Sequential()
network.add(layers.Dense(512,activation="relu", input_shape=(28 * 28,)))
network.add(layers.Dense(100,activation="relu"))




network.add(layers.Dense(10,activation="softmax"))

In [ ]:
network.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 100)               51300     
                                                                 
 dense_2 (Dense)             (None, 10)                1010      
                                                                 
Total params: 454230 (1.73 MB)
Trainable params: 454230 (1.73 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# choose the optimizer and loss function to use during the training
network.compile(optimizer="adam",
                loss="categorical_crossentropy",
                metrics=["accuracy"])

In [ ]:
# prepare dataset in the correct format

In [ ]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [ ]:
# data transformation   transform the image to a vector for train and test data
train_images = train_images.reshape(60000,28 * 28)
# change value to float and divide / 255 to have number between 0 1
train_images = train_images.astype("float32") / 255

test_images = test_images.reshape(10000,28 * 28)
test_images = test_images.astype("float32") / 255

In [ ]:
# original labels
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
import tensorflow as tf
# in order to use categorical cross entropy need to change output ( similar to one hot encoding )
train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

In [ ]:
# One hot encoding for '5' >> 0 0 0 0 0 1 0 0 0 0
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
train_labels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
network.fit(train_images, train_labels,epochs=5, batch_size=10000)

Epoch 1/5
6/6 [==============================] - 7s 62ms/step - loss: 1.7286 - accuracy: 0.5498
Epoch 2/5
6/6 [==============================] - 0s 58ms/step - loss: 0.7488 - accuracy: 0.8189
Epoch 3/5
6/6 [==============================] - 0s 54ms/step - loss: 0.4371 - accuracy: 0.8729
Epoch 4/5
6/6 [==============================] - 0s 51ms/step - loss: 0.3450 - accuracy: 0.8991
Epoch 5/5
6/6 [==============================] - 0s 44ms/step - loss: 0.2983 - accuracy: 0.9130


In [ ]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 4s 11ms/step - loss: 0.2708 - accuracy: 0.9222


In [ ]:
print("test accuracy", test_acc)

test accuracy 0.9222000241279602


In [ ]:
# neural network architectures :  ( Keras and torch )

## binary classification
  # input shape base on   X.shape[1] ( number of columns )
  # hidden layers  activation function ReLU (easy to compute )
  # output shape 1 activation function sigmoid  loss binary_cross entropy
  ##///     output shape 2 activation function loss  categorical_cross_entropy

## multiclass classification
  # input shape base on   X.shape[1] ( number of columns )
  # hidden layers  activation function ReLU (easy to compute )
  # output shape n_classes of output  activation function softmax   loss categorical_cross_entropy

# regression
  # input ...
  # hidden ...
  # output 1 neuron  activation Relu   loss Mean_square_error


In [ ]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

# computer vision

In [ ]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [ ]:
# dataset preparation normalization numbers between 0 and 1
train_images = train_images.astype("float32") / 255
test_images = test_images.astype("float32") / 255

In [ ]:
import tensorflow as tf
train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

In [ ]:
# CNN neural network
network = models.Sequential()
network.add(layers.Conv2D(8,3,activation="relu",input_shape=(28,28,1))) # 8 filters  kernel_size 3 (3,3)
network.add(layers.MaxPool2D(2))
network.add(layers.Conv2D(15,3,activation="relu"))
network.add(layers.MaxPool2D(2))
network.add(layers.Conv2D(20,3,activation="relu"))
network.add(layers.MaxPool2D(2))
network.add(layers.Flatten())
network.add(layers.Dense(100,activation="relu"))
network.add(layers.Dense(10,activation="softmax"))

In [ ]:
network.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 26, 26, 8)         80        
                                                                 
 max_pooling2d_11 (MaxPooli  (None, 13, 13, 8)         0         
 ng2D)                                                           
                                                                 
 conv2d_12 (Conv2D)          (None, 11, 11, 15)        1095      
                                                                 
 max_pooling2d_12 (MaxPooli  (None, 5, 5, 15)          0         
 ng2D)                                                           
                                                                 
 conv2d_13 (Conv2D)          (None, 3, 3, 20)          2720      
                                                                 
 max_pooling2d_13 (MaxPooli  (None, 1, 1, 20)         

In [ ]:
network.compile(optimizer="adam",
                loss="categorical_crossentropy",
                metrics=["accuracy"])

In [ ]:
# train model
network.fit(train_images, train_labels, epochs=5,batch_size=600)

Epoch 1/5
100/100 [==============================] - 2s 7ms/step - loss: 1.5162 - accuracy: 0.5121
Epoch 2/5
100/100 [==============================] - 1s 6ms/step - loss: 0.4017 - accuracy: 0.8790
Epoch 3/5
100/100 [==============================] - 1s 5ms/step - loss: 0.2603 - accuracy: 0.9219
Epoch 4/5
100/100 [==============================] - 1s 5ms/step - loss: 0.2080 - accuracy: 0.9366
Epoch 5/5
100/100 [==============================] - 1s 5ms/step - loss: 0.1799 - accuracy: 0.9452


In [ ]:
# transfert learning :

# use 'pretrained models'
# >>> fine tuning  ( training of a pretrained model )

In [ ]:
# first step to work on computer vision problem
# task identification :
#     image classification : give label to a whole image ex : cat, dog, truck ...
#     object detection : detect an object and bounding box in the image
#    semantic segmentation : assign each pixel in the image to a specific class or object



## check for SOTA ( state of the ar models )
## check for models trained on benchmarks ( well known datasets)

# use pretrained models ( weights of the model should not be random) >> Fine Tuning


# no need no for large dataset for training :

In [ ]:
# object detection

# My own dataset preparation : data annotations
   # follow a generic format :
                # COCO dataset format
                # Pscal VOC format

     #  use a software to faciliate the task of annotation and export data directly to the different format
     # https://labelstud.io/guide/get_started.html#Quick-start
     # https://github.com/jsbroks/coco-annotator

     # we can apply active learning using label studio
     # https://blog.cloudfactory.com/active-learning-tackling-ml-data-annotation-challenges


In [ ]:
# choose model based on SOTA model performance on benchmarks

# fine tuning the models : train the pretrained model on our own dataset

# test the model : accuracy, f1 score ... AP ( coco datset object detection metrics )

# model deployment : put model in production mode  Web server accessed in the internet , edge device Iot

# always collect information and evaluate the models : monotoring

In [ ]:
# machine learning yearning book
# https://github.com/ajaymache/machine-learning-yearning/blob/master/full%20book/machine-learning-yearning.pdf

In [ ]:
# object detection with detectron 2
# https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

#
#  https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html
# model zoo

In [ ]:
# https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md

In [ ]:
# other libraries to use for object detection
# https://github.com/open-mmlab/mmdetection

In [ ]:
# presentation link CNN.pdf
# https://drive.google.com/file/d/1ZP1RWXKrM3H-u4F3wS9m0PmwT0YWVOIz/view?usp=drive_link

# natural language processing

In [ ]:
import pandas as pd

In [ ]:
# linux copy command to copy a file from google drive to the current directory  ( put ! mark befor commands)
!cp /content/drive/MyDrive/datasets/Sentiment.csv .

In [ ]:
data = pd.read_csv("Sentiment.csv")

In [ ]:
data

id               candidate  candidate_confidence relevant_yn  \
0          1  No candidate mentioned                1.0000         yes   
1          2            Scott Walker                1.0000         yes   
2          3  No candidate mentioned                1.0000         yes   
3          4  No candidate mentioned                1.0000         yes   
4          5            Donald Trump                1.0000         yes   
...      ...                     ...                   ...         ...   
13866  13867  No candidate mentioned                1.0000         yes   
13867  13868           Mike Huckabee                0.9611         yes   
13868  13869                Ted Cruz                1.0000         yes   
13869  13870            Donald Trump                1.0000         yes   
13870  13871                Ted Cruz                0.9242         yes   

       relevant_yn_confidence sentiment  sentiment_confidence  \
0                      1.0000   Neutral                0.6578   
1                      1.0000  Positive                0.6333   
2                      1.0000   Neutral                0.6629   
3                      1.0000  Positive                1.0000   
4                      1.0000  Positive                0.7045   
...                       ...       ...                   ...   
13866                  1.0000  Negative                0.7991   
13867                  1.0000  Positive                0.7302   
13868                  1.0000  Positive                0.8051   
13869                  1.0000  Negative                1.0000   
13870                  0.9614  Positive                0.9614   

                             subject_matter  subject_matter_confidence  \
0                         None of the above                     1.0000   
1                         None of the above                     1.0000   
2                         None of the above                     0.6629   
3                         None of the above                     0.7039   
4                         None of the above                     1.0000   
...                                     ...                        ...   
13866                              Abortion                     0.6014   
13867                     None of the above                     0.9229   
13868                     None of the above                     0.9647   
13869  Women's Issues (not abortion though)                     0.9202   
13870                     None of the above                     0.9242   

               candidate_gold  ... relevant_yn_gold retweet_count  \
0                         NaN  ...              NaN             5   
1                         NaN  ...              NaN            26   
2                         NaN  ...              NaN            27   
3                         NaN  ...              NaN           138   
4                         NaN  ...              NaN           156   
...                       ...  ...              ...           ...   
13866  No candidate mentioned  ...              yes             7   
13867           Mike Huckabee  ...              yes             1   
13868                Ted Cruz  ...              yes            67   
13869            Donald Trump  ...              yes           149   
13870                Ted Cruz  ...              yes            65   

          sentiment_gold                             subject_matter_gold  \
0                    NaN                                             NaN   
1                    NaN                                             NaN   
2                    NaN                                             NaN   
3                    NaN                                             NaN   
4                    NaN                                             NaN   
...                  ...                                             ...   
13866           Negative  Abortion\nWomen's Issues (not abortion though)   
13867         

In [ ]:
data = data[["text", "sentiment"]]

In [ ]:
data

text sentiment
0      RT @NancyLeeGrahn: How did everyone feel about...   Neutral
1      RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
2      RT @TJMShow: No mention of Tamir Rice and the ...   Neutral
3      RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4      RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive
...                                                  ...       ...
13866  RT @cappy_yarbrough: Love to see men who will ...  Negative
13867  RT @georgehenryw: Who thought Huckabee exceede...  Positive
13868  RT @Lrihendry: #TedCruz As President, I will a...  Positive
13869  RT @JRehling: #GOPDebate Donald Trump says tha...  Negative
13870  RT @Lrihendry: #TedCruz headed into the Presid...  Positive

[13871 rows x 2 columns]

In [ ]:
# need to eliminate uppercase : How, how 2 differents words

In [ ]:
data["text"] = data["text"].apply( lambda x: x.lower()) # lambda function in order to declare a function implicitly without proper declartion

<ipython-input-8-06e4ec08e937>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"] = data["text"].apply( lambda x: x.lower())


In [ ]:
data

text sentiment
0      rt @nancyleegrahn: how did everyone feel about...   Neutral
1      rt @scottwalker: didn't catch the full #gopdeb...  Positive
2      rt @tjmshow: no mention of tamir rice and the ...   Neutral
3      rt @robgeorge: that carly fiorina is trending ...  Positive
4      rt @danscavino: #gopdebate w/ @realdonaldtrump...  Positive
...                                                  ...       ...
13866  rt @cappy_yarbrough: love to see men who will ...  Negative
13867  rt @georgehenryw: who thought huckabee exceede...  Positive
13868  rt @lrihendry: #tedcruz as president, i will a...  Positive
13869  rt @jrehling: #gopdebate donald trump says tha...  Negative
13870  rt @lrihendry: #tedcruz headed into the presid...  Positive

[13871 rows x 2 columns]

In [ ]:
# iloc to select element index 1  column 'text'
data.iloc[1]["text"]

"rt @scottwalker: didn't catch the full #gopdebate last night. here are some of scott's best lines in 90 seconds. #walker16 http://t.co/zsff…"

In [ ]:
# https://regex101.com/
import re
data["text"] = data["text"].apply( lambda x : re.sub('[^a-z0-9\s]','',x)) # replace special character not present in the list with empty string for every text

<ipython-input-11-e19fc6586bf0>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"] = data["text"].apply( lambda x : re.sub('[^a-z0-9\s]','',x)) # replace special character not present in the list with empty string for every text


In [ ]:
data

text sentiment
0      rt nancyleegrahn how did everyone feel about t...   Neutral
1      rt scottwalker didnt catch the full gopdebate ...  Positive
2      rt tjmshow no mention of tamir rice and the go...   Neutral
3      rt robgeorge that carly fiorina is trending  h...  Positive
4      rt danscavino gopdebate w realdonaldtrump deli...  Positive
...                                                  ...       ...
13866  rt cappyyarbrough love to see men who will nev...  Negative
13867  rt georgehenryw who thought huckabee exceeded ...  Positive
13868  rt lrihendry tedcruz as president i will alway...  Positive
13869  rt jrehling gopdebate donald trump says that h...  Negative
13870  rt lrihendry tedcruz headed into the president...  Positive

[13871 rows x 2 columns]

In [ ]:
for idx, row in data.iterrows():
    row[0] = row[0].replace("rt","")
    #print(row[0])

In [ ]:
data

text sentiment
0      rt nancyleegrahn how did everyone feel about t...   Neutral
1      rt scottwalker didnt catch the full gopdebate ...  Positive
2      rt tjmshow no mention of tamir rice and the go...   Neutral
3      rt robgeorge that carly fiorina is trending  h...  Positive
4      rt danscavino gopdebate w realdonaldtrump deli...  Positive
...                                                  ...       ...
13866  rt cappyyarbrough love to see men who will nev...  Negative
13867  rt georgehenryw who thought huckabee exceeded ...  Positive
13868  rt lrihendry tedcruz as president i will alway...  Positive
13869  rt jrehling gopdebate donald trump says that h...  Negative
13870  rt lrihendry tedcruz headed into the president...  Positive

[13871 rows x 2 columns]

In [ ]:
data

text sentiment
0      rt nancyleegrahn how did everyone feel about t...   Neutral
1      rt scottwalker didnt catch the full gopdebate ...  Positive
2      rt tjmshow no mention of tamir rice and the go...   Neutral
3      rt robgeorge that carly fiorina is trending  h...  Positive
4      rt danscavino gopdebate w realdonaldtrump deli...  Positive
...                                                  ...       ...
13866  rt cappyyarbrough love to see men who will nev...  Negative
13867  rt georgehenryw who thought huckabee exceeded ...  Positive
13868  rt lrihendry tedcruz as president i will alway...  Positive
13869  rt jrehling gopdebate donald trump says that h...  Negative
13870  rt lrihendry tedcruz headed into the president...  Positive

[13871 rows x 2 columns]

In [ ]:
data = data[data["sentiment"] != "Neutral"]

In [ ]:
data

text sentiment
1      rt scottwalker didnt catch the full gopdebate ...  Positive
3      rt robgeorge that carly fiorina is trending  h...  Positive
4      rt danscavino gopdebate w realdonaldtrump deli...  Positive
5      rt gregabbotttx tedcruz on my first day i will...  Positive
6      rt warriorwoman91 i liked her and was happy wh...  Negative
...                                                  ...       ...
13866  rt cappyyarbrough love to see men who will nev...  Negative
13867  rt georgehenryw who thought huckabee exceeded ...  Positive
13868  rt lrihendry tedcruz as president i will alway...  Positive
13869  rt jrehling gopdebate donald trump says that h...  Negative
13870  rt lrihendry tedcruz headed into the president...  Positive

[10729 rows x 2 columns]

In [ ]:
y = pd.get_dummies(data["sentiment"],drop_first=True,dtype=int)

In [ ]:
y

Positive
1             1
3             1
4             1
5             1
6             0
...         ...
13866         0
13867         1
13868         1
13869         0
13870         1

[10729 rows x 1 columns]

In [ ]:
!pip show pandas

Name: pandas
Version: 2.0.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: 
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License
        
        Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
        All rights reserved.
        
        Copyright (c) 2011-2023, Open source contributors.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials provided with the distrib

In [ ]:
y

Positive
1             1
3             1
4             1
5             1
6             0
...         ...
13866         0
13867         1
13868         1
13869         0
13870         1

[10729 rows x 1 columns]

In [ ]:
# import libraries
from  sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from keras.models import Sequential
from sklearn.model_selection import train_test_split
#from keras.utils.np_utils import to_categorical
from tensorflow.keras.utils import pad_sequences

In [ ]:
max_features = 2000
tokenizer = Tokenizer(num_words=max_features) # vocab size

In [ ]:
tokenizer.fit_on_texts(data["text"])

In [ ]:
# test the tokenization
tokenizer.texts_to_sequences(["this is very nice", 'this was bad','this was bien'])

[[21, 6, 101, 691], [21, 22, 343], [21, 22]]

In [ ]:
X = tokenizer.texts_to_sequences(data["text"].values)

In [ ]:
X

[[3,
  359,
  121,
  1,
  713,
  2,
  40,
  59,
  235,
  37,
  208,
  7,
  173,
  1742,
  13,
  1303,
  1387,
  734],
 [3, 17, 282, 250, 6, 809, 103, 170, 27, 134, 7, 1, 171, 13, 2, 232, 714, 18],
 [3, 1244, 2, 308, 24, 1921, 1, 1608, 214, 13, 1, 693, 7, 184, 205, 367, 680],
 [3,
  126,
  18,
  54,
  261,
  405,
  10,
  83,
  301,
  435,
  1304,
  1743,
  1134,
  63,
  1922,
  192,
  2,
  52],
 [3,
  10,
  1135,
  170,
  9,
  22,
  1305,
  64,
  10,
  605,
  186,
  22,
  187,
  5,
  35,
  1,
  556,
  20,
  810,
  2,
  45,
  735],
 [13, 1, 3, 168, 97, 541, 35, 1, 104, 606, 53, 60, 1744, 8, 18, 607, 2],
 [3, 40, 147, 27, 811, 14, 2, 910],
 [24, 13, 47, 17],
 [3, 38, 1923, 48, 5, 1088, 21, 70, 2, 173, 542, 7, 1, 59, 274, 332],
 [32, 1188, 54, 446, 23, 55, 144, 1, 2, 22],
 [3, 661, 10, 520, 302, 166, 56, 13, 1306, 181, 14, 48, 2],
 [303, 368, 1, 7, 879, 15, 93, 458, 269, 6, 270, 2],
 [3, 265, 459, 951, 15, 446, 23, 108, 13, 18, 2, 468],
 [3, 608, 53, 185, 130, 174, 109, 30, 1, 2, 52, 276, 

In [ ]:
X = pad_sequences(X)

In [ ]:
X.shape

(10729, 28)

In [ ]:
X

array([[   0,    0,    0, ..., 1303, 1387,  734],
       [   0,    0,    0, ...,  232,  714,   18],
       [   0,    0,    0, ...,  205,  367,  680],
       ...,
       [   0,    0,    0, ...,   72,   66,    4],
       [   0,    0,    0, ..., 1006, 1399,   74],
       [   0,    0,    0, ...,  195,    4,  712]], dtype=int32)

In [ ]:
embed_dim = 128
lstm_output = 196

model = Sequential()
# embedding vectorial respresntation of the words
# the model would learn the best representation for the specific task
# number of parameters 2000 vocab size 128 embd_dim  >>> N_paramets 2000 * 128
model.add(Embedding(max_features,embed_dim, input_length= X.shape[1]))
model.add(SpatialDropout1D(0.4))
model.add(LSTM(lstm_output,dropout=0.2))
#model.add(LSTM(lstm_output,dropout=0.2))
model.add(Dense(10, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 28, 128)           256000    
                                                                 
 spatial_dropout1d (Spatial  (None, 28, 128)           0         
 Dropout1D)                                                      
                                                                 
 lstm (LSTM)                 (None, 196)               254800    
                                                                 
 dense (Dense)               (None, 10)                1970      
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 512781 (1.96 MB)
Trainable params: 512781 (1.96 MB)
Non-trainable params: 0 (0.00 Byte)
____________________

In [ ]:
model.compile(loss="binary_crossentropy",optimizer="adam", metrics=["accuracy"])

In [ ]:
X_train, X_test, y_train ,y_test = train_test_split(X, y)

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=64)

Epoch 1/10
126/126 [==============================] - 18s 113ms/step - loss: 0.4539 - accuracy: 0.8127
Epoch 2/10
126/126 [==============================] - 19s 148ms/step - loss: 0.3198 - accuracy: 0.8639
Epoch 3/10
126/126 [==============================] - 17s 136ms/step - loss: 0.2797 - accuracy: 0.8832
Epoch 4/10
126/126 [==============================] - 17s 133ms/step - loss: 0.2510 - accuracy: 0.8946
Epoch 5/10
126/126 [==============================] - 14s 114ms/step - loss: 0.2345 - accuracy: 0.8985
Epoch 6/10
126/126 [==============================] - 16s 125ms/step - loss: 0.2200 - accuracy: 0.9075
Epoch 7/10
126/126 [==============================] - 18s 139ms/step - loss: 0.1960 - accuracy: 0.9161
Epoch 8/10
126/126 [==============================] - 18s 143ms/step - loss: 0.1817 - accuracy: 0.9243
Epoch 9/10
126/126 [==============================] - 16s 127ms/step - loss: 0.1690 - accuracy: 0.9262
Epoch 10/10
126/126 [==============================] - 15s 120ms/step - l

In [ ]:
# encoder architecture
# sentences >>> ( tokenizer ) >>> tokens >>> (embedding) Dense vectorial representation
# embedding layer start with random values in the table during training learn to optimize
# the values
# >>> RNN >>   encode result in a vector >> use Dense layers for classification


In [ ]:
# embedding from scratch learn from training of the neural network
# use pretrained embedding
# ex Word2Vec  Glove  FastText
# https://jalammar.github.io/illustrated-word2vec/
# https://nlp.stanford.edu/projects/glove/
# https://fasttext.cc/docs/en/crawl-vectors.html

In [ ]:
# how to get data to make training

# scrapping
 #  beautiful soup https://www.crummy.com/software/BeautifulSoup/bs4/doc/
 # https://scrapy.org/
 # selenium https://www.selenium.dev/

# API  (Application porgamming Interface
# https://python-twitter.readthedocs.io/en/latest/getting_started.html

In [ ]:
# spacy for NLP modeling

In [ ]:
# state of the Art NLP models : transformers   ( paper : attention is all you need )
# https://jalammar.github.io/illustrated-transformer/

In [ ]:
# pip install -U spacy
# python -m spacy download en_core_web_sm
import spacy

# Load English tokenizer, tagger, parser and NER
nlp = spacy.load("en_core_web_sm")

# Process whole documents
text = ("When Sebastian Thrun started working on self-driving cars at "
        "Google in 2007, few people outside of the company took him "
        "seriously. “I can tell you very senior CEOs of major American "
        "car companies would shake my hand and turn away because I wasn’t "
        "worth talking to,” said Thrun, in an interview with Recode earlier "
        "this week.")
doc = nlp(text)

# Analyze syntax
print("Noun phrases:", [chunk.text for chunk in doc.noun_chunks])
print("Verbs:", [token.lemma_ for token in doc if token.pos_ == "VERB"])

# Find named entities, phrases and concepts
for entity in doc.ents:
    print(entity.text, entity.label_)

Noun phrases: ['Sebastian Thrun', 'self-driving cars', 'Google', 'few people', 'the company', 'him', 'I', 'you', 'very senior CEOs', 'major American car companies', 'my hand', 'I', 'Thrun', 'an interview', 'Recode']
Verbs: ['start', 'work', 'drive', 'take', 'tell', 'shake', 'turn', 'talk', 'say']
Sebastian Thrun PERSON
Google ORG
2007 DATE
American NORP
Thrun PERSON
Recode ORG
earlier this week DATE


In [ ]:
 # spacy course
#  https://course.spacy.io/en/

In [ ]:
# hugging face   transformers
# https://huggingface.co/

In [ ]:
# https://huggingface.co/learn/nlp-course/chapter1/1

In [ ]:
# https://github.com/graykode/nlp-roadmap

In [ ]:
# https://paperswithcode.com/area/natural-language-processing

In [ ]:
# gradio for testing and developement
# https://www.gradio.app/
# it s used wit hugging face spaces https://huggingface.co/spaces

In [ ]:
# deployement
# API :    flask ,    FastApi

# https://fastapi.tiangolo.com/

In [ ]:
# functions

# model.pedict(image )


# make a function that would be called when a client make a request
# def predict(request)
#   extract image from request
#   do the prediction model.predict(image)
#  return prediction result avec appropriate formatting
# flask or FastApi would return the result to the client
# i can test it with Postman / in
 # https://insomnia.rest/    for testing the API
 # https://www.postman.com/