<a href="https://colab.research.google.com/github/123rabida123/Deep-Learning/blob/main/DeepLearning_Mai24-05-05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import mnist

In [ ]:
(train_images, train_labels), ( test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
train_images.shape

(60000, 28, 28)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
# model architecture
from keras import models, layers

In [ ]:
network = models.Sequential()
network.add(layers.Dense(512,activation="relu", input_shape=(28 * 28,)))
network.add(layers.Dense(100,activation="relu"))




network.add(layers.Dense(10,activation="softmax"))

In [ ]:
network.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 100)               51300     
                                                                 
 dense_2 (Dense)             (None, 10)                1010      
                                                                 
Total params: 454230 (1.73 MB)
Trainable params: 454230 (1.73 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# choose the optimizer and loss function to use during the training
network.compile(optimizer="adam",
                loss="categorical_crossentropy",
                metrics=["accuracy"])

In [ ]:
# prepare dataset in the correct format

In [ ]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [ ]:
# data transformation   transform the image to a vector for train and test data
train_images = train_images.reshape(60000,28 * 28)
# change value to float and divide / 255 to have number between 0 1
train_images = train_images.astype("float32") / 255

test_images = test_images.reshape(10000,28 * 28)
test_images = test_images.astype("float32") / 255

In [ ]:
# original labels
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
import tensorflow as tf
# in order to use categorical cross entropy need to change output ( similar to one hot encoding )
train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

In [ ]:
# One hot encoding for '5' >> 0 0 0 0 0 1 0 0 0 0
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
train_labels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
network.fit(train_images, train_labels,epochs=5, batch_size=10000)

Epoch 1/5
6/6 [==============================] - 7s 62ms/step - loss: 1.7286 - accuracy: 0.5498
Epoch 2/5
6/6 [==============================] - 0s 58ms/step - loss: 0.7488 - accuracy: 0.8189
Epoch 3/5
6/6 [==============================] - 0s 54ms/step - loss: 0.4371 - accuracy: 0.8729
Epoch 4/5
6/6 [==============================] - 0s 51ms/step - loss: 0.3450 - accuracy: 0.8991
Epoch 5/5
6/6 [==============================] - 0s 44ms/step - loss: 0.2983 - accuracy: 0.9130


In [ ]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 4s 11ms/step - loss: 0.2708 - accuracy: 0.9222


In [ ]:
print("test accuracy", test_acc)

test accuracy 0.9222000241279602


In [ ]:
# neural network architectures :  ( Keras and torch )

## binary classification
  # input shape base on   X.shape[1] ( number of columns )
  # hidden layers  activation function ReLU (easy to compute )
  # output shape 1 activation function sigmoid  loss binary_cross entropy
  ##///     output shape 2 activation function loss  categorical_cross_entropy

## multiclass classification
  # input shape base on   X.shape[1] ( number of columns )
  # hidden layers  activation function ReLU (easy to compute )
  # output shape n_classes of output  activation function softmax   loss categorical_cross_entropy

# regression
  # input ...
  # hidden ...
  # output 1 neuron  activation Relu   loss Mean_square_error


In [ ]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

# computer vision

In [ ]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [ ]:
# dataset preparation normalization numbers between 0 and 1
train_images = train_images.astype("float32") / 255
test_images = test_images.astype("float32") / 255

In [ ]:
import tensorflow as tf
train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

In [ ]:
# CNN neural network
network = models.Sequential()
network.add(layers.Conv2D(8,3,activation="relu",input_shape=(28,28,1))) # 8 filters  kernel_size 3 (3,3)
network.add(layers.MaxPool2D(2))
network.add(layers.Conv2D(15,3,activation="relu"))
network.add(layers.MaxPool2D(2))
network.add(layers.Conv2D(20,3,activation="relu"))
network.add(layers.MaxPool2D(2))
network.add(layers.Flatten())
network.add(layers.Dense(100,activation="relu"))
network.add(layers.Dense(10,activation="softmax"))

In [ ]:
network.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 26, 26, 8)         80        
                                                                 
 max_pooling2d_11 (MaxPooli  (None, 13, 13, 8)         0         
 ng2D)                                                           
                                                                 
 conv2d_12 (Conv2D)          (None, 11, 11, 15)        1095      
                                                                 
 max_pooling2d_12 (MaxPooli  (None, 5, 5, 15)          0         
 ng2D)                                                           
                                                                 
 conv2d_13 (Conv2D)          (None, 3, 3, 20)          2720      
                                                                 
 max_pooling2d_13 (MaxPooli  (None, 1, 1, 20)         

In [ ]:
network.compile(optimizer="adam",
                loss="categorical_crossentropy",
                metrics=["accuracy"])

In [ ]:
# train model
network.fit(train_images, train_labels, epochs=5,batch_size=600)

Epoch 1/5
100/100 [==============================] - 2s 7ms/step - loss: 1.5162 - accuracy: 0.5121
Epoch 2/5
100/100 [==============================] - 1s 6ms/step - loss: 0.4017 - accuracy: 0.8790
Epoch 3/5
100/100 [==============================] - 1s 5ms/step - loss: 0.2603 - accuracy: 0.9219
Epoch 4/5
100/100 [==============================] - 1s 5ms/step - loss: 0.2080 - accuracy: 0.9366
Epoch 5/5
100/100 [==============================] - 1s 5ms/step - loss: 0.1799 - accuracy: 0.9452


In [ ]:
# transfert learning :

# use 'pretrained models'
# >>> fine tuning  ( training of a pretrained model )

In [ ]:
# first step to work on computer vision problem
# task identification :
#     image classification : give label to a whole image ex : cat, dog, truck ...
#     object detection : detect an object and bounding box in the image
#    semantic segmentation : assign each pixel in the image to a specific class or object



## check for SOTA ( state of the ar models )
## check for models trained on benchmarks ( well known datasets)

# use pretrained models ( weights of the model should not be random) >> Fine Tuning


# no need no for large dataset for training :

In [ ]:
# object detection

# My own dataset preparation : data annotations
   # follow a generic format :
                # COCO dataset format
                # Pscal VOC format

     #  use a software to faciliate the task of annotation and export data directly to the different format
     # https://labelstud.io/guide/get_started.html#Quick-start
     # https://github.com/jsbroks/coco-annotator

     # we can apply active learning using label studio
     # https://blog.cloudfactory.com/active-learning-tackling-ml-data-annotation-challenges


In [ ]:
# choose model based on SOTA model performance on benchmarks

# fine tuning the models : train the pretrained model on our own dataset

# test the model : accuracy, f1 score ... AP ( coco datset object detection metrics )

# model deployment : put model in production mode  Web server accessed in the internet , edge device Iot

# always collect information and evaluate the models : monotoring

In [ ]:
# machine learning yearning book
# https://github.com/ajaymache/machine-learning-yearning/blob/master/full%20book/machine-learning-yearning.pdf

In [ ]:
# object detection with detectron 2
# https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

#
#  https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html
# model zoo

In [ ]:
# https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md

In [ ]:
# other libraries to use for object detection
# https://github.com/open-mmlab/mmdetection

In [ ]:
# presentation link CNN.pdf
# https://drive.google.com/file/d/1ZP1RWXKrM3H-u4F3wS9m0PmwT0YWVOIz/view?usp=drive_link

# natural language processing

In [ ]:
import pandas as pd

In [ ]:
# linux copy command to copy a file from google drive to the current directory  ( put ! mark befor commands)
!cp /content/drive/MyDrive/datasets/Sentiment.csv .

In [ ]:
data = pd.read_csv("Sentiment.csv")

In [ ]:
data

id               candidate  candidate_confidence relevant_yn  \
0          1  No candidate mentioned                1.0000         yes   
1          2            Scott Walker                1.0000         yes   
2          3  No candidate mentioned                1.0000         yes   
3          4  No candidate mentioned                1.0000         yes   
4          5            Donald Trump                1.0000         yes   
...      ...                     ...                   ...         ...   
13866  13867  No candidate mentioned                1.0000         yes   
13867  13868           Mike Huckabee                0.9611         yes   
13868  13869                Ted Cruz                1.0000         yes   
13869  13870            Donald Trump                1.0000         yes   
13870  13871                Ted Cruz                0.9242         yes   

       relevant_yn_confidence sentiment  sentiment_confidence  \
0                      1.0000   Neutral                0.6578   
1                      1.0000  Positive                0.6333   
2                      1.0000   Neutral                0.6629   
3                      1.0000  Positive                1.0000   
4                      1.0000  Positive                0.7045   
...                       ...       ...                   ...   
13866                  1.0000  Negative                0.7991   
13867                  1.0000  Positive                0.7302   
13868                  1.0000  Positive                0.8051   
13869                  1.0000  Negative                1.0000   
13870                  0.9614  Positive                0.9614   

                             subject_matter  subject_matter_confidence  \
0                         None of the above                     1.0000   
1                         None of the above                     1.0000   
2                         None of the above                     0.6629   
3                         None of the above                     0.7039   
4                         None of the above                     1.0000   
...                                     ...                        ...   
13866                              Abortion                     0.6014   
13867                     None of the above                     0.9229   
13868                     None of the above                     0.9647   
13869  Women's Issues (not abortion though)                     0.9202   
13870                     None of the above                     0.9242   

               candidate_gold  ... relevant_yn_gold retweet_count  \
0                         NaN  ...              NaN             5   
1                         NaN  ...              NaN            26   
2                         NaN  ...              NaN            27   
3                         NaN  ...              NaN           138   
4                         NaN  ...              NaN           156   
...                       ...  ...              ...           ...   
13866  No candidate mentioned  ...              yes             7   
13867           Mike Huckabee  ...              yes             1   
13868                Ted Cruz  ...              yes            67   
13869            Donald Trump  ...              yes           149   
13870                Ted Cruz  ...              yes            65   

          sentiment_gold                             subject_matter_gold  \
0                    NaN                                             NaN   
1                    NaN                                             NaN   
2                    NaN                                             NaN   
3                    NaN                                             NaN   
4                    NaN                                             NaN   
...                  ...                                             ...   
13866           Negative  Abortion\nWomen's Issues (not abortion though)   
13867         

In [ ]:
data = data[["text", "sentiment"]]

In [ ]:
data

text sentiment
0      RT @NancyLeeGrahn: How did everyone feel about...   Neutral
1      RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
2      RT @TJMShow: No mention of Tamir Rice and the ...   Neutral
3      RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4      RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive
...                                                  ...       ...
13866  RT @cappy_yarbrough: Love to see men who will ...  Negative
13867  RT @georgehenryw: Who thought Huckabee exceede...  Positive
13868  RT @Lrihendry: #TedCruz As President, I will a...  Positive
13869  RT @JRehling: #GOPDebate Donald Trump says tha...  Negative
13870  RT @Lrihendry: #TedCruz headed into the Presid...  Positive

[13871 rows x 2 columns]

In [ ]:
# need to eliminate uppercase : How, how 2 differents words

In [ ]:
data["text"] = data["text"].apply( lambda x: x.lower()) # lambda function

<ipython-input-8-06e4ec08e937>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["text"] = data["text"].apply( lambda x: x.lower())


In [ ]:
data

text sentiment
0      rt @nancyleegrahn: how did everyone feel about...   Neutral
1      rt @scottwalker: didn't catch the full #gopdeb...  Positive
2      rt @tjmshow: no mention of tamir rice and the ...   Neutral
3      rt @robgeorge: that carly fiorina is trending ...  Positive
4      rt @danscavino: #gopdebate w/ @realdonaldtrump...  Positive
...                                                  ...       ...
13866  rt @cappy_yarbrough: love to see men who will ...  Negative
13867  rt @georgehenryw: who thought huckabee exceede...  Positive
13868  rt @lrihendry: #tedcruz as president, i will a...  Positive
13869  rt @jrehling: #gopdebate donald trump says tha...  Negative
13870  rt @lrihendry: #tedcruz headed into the presid...  Positive

[13871 rows x 2 columns]